### ISSUE TITLE
Useless line

### ISSUE THREAD

**Issue by smaftoul** [sjourdan/hadolint-docker#1]
https://github.com/sjourdan/hadolint-docker/blob/c85349ec6c6efd2e6dadf459d9c9c3b1eab4a8d0/Dockerfile#L16

Is useless, because of https://github.com/sjourdan/hadolint-docker/blob/c85349ec6c6efd2e6dadf459d9c9c3b1eab4a8d0/Dockerfile#L13

**Comment by sjourdan** [comment]
You're right @smaftoul  - I should deprecate anyway this docker image as the original maintainer is now providing a nice Docker image. 

https://github.com/hadolint/hadolint/pull/97
